### ISSUE TITLE
CPP source

### ISSUE THREAD

**Issue by tsangz189** [seetaface/SeetaFaceEngine2#15]
I would like to edit some lines of code. Is it possible to get the cpp src file?
Thank you

**Comment by rbbernardino** [comment]
I checked the chinese comments and found that this account has been abandoned and there is another one currently being maintained:
https://github.com/seetafaceengine/SeetaFace2

**Comment by Thanh-Binh** [comment]
@rbbernardino thanks for this link?
Any code for training new models?
