### ISSUE TITLE
Android libPointDetectorJni.so库文件函数入口错误

### ISSUE THREAD

**Issue by catchingSun** [seetaface/SeetaFaceEngine2#17]
com.seeta.sdk.PointDetector2运行错误
**Error**：No implementation found for void com.seeta.sdk.PointDetector2.construct(java.lang.String) (tried Java_com_seeta_sdk_PointDetector2_construct and Java_com_seeta_sdk_PointDetector2_construct__Ljava_lang_String_2)

com.seeta.sdk.FaceDetector2运行正常

**Comment by seetaface** [comment]
The problem has been repaired and thank you for your support. ^_^
