### ISSUE TITLE
希望能提供编译说明

### ISSUE THREAD

**Issue by dengly** [seetaface/SeetaFaceEngine2#31]
希望能提供Android、Windows、Linux的编译说明。
另本人使用的是Mac OS X，如果Linux能编译的话，理论上Mac OS X应该也是能编译的。

**Comment by northeastsquare** [comment]
gcc版本不同都很难编译过去，gcc版本应该使用ubuntu 16.04 里面的版本。
opencv 2.4.6, protobuf 2.6.1, 使用vs2013编译过去了
