### ISSUE TITLE
除了人脸库限制10人，程序还有那些坑希望厂家说明！

### ISSUE THREAD

**Issue by ccrop** [seetaface/SeetaFaceEngine2#6]
除了人脸库限制10人，程序还有那些坑希望厂家说明！

**Comment by YihaoWEI** [comment]
山老师不容易了，什么时候变厂家了2333

**Comment by seetaface** [comment]
根据大家反馈的情况，我们会在月底放大人脸库数量，并开放无限底库试用申请渠道。届时相关内容会在 [人脸识别文档页面](https://github.com/seetaface/SeetaFaceEngine2/blob/master/FaceIdentification/README.md) 更新。

**Comment by ccrop** [comment]
期待
